### ISSUE TITLE
AssertionError: Please run: python retrieve.py

### ISSUE THREAD

**Issue by sjz1** [SKTFellowship/SKT_Fellowship#10]
Custom Diffusion에서 retrieve.py를 통해 regular data를 받았음에도 불구하고 다음과 같은 에러가 나오는 경우가 있습니다
`Traceback (most recent call last):
  File "train_custom_diffusion.py", line 1337, in <module>
    main(args)
  File "train_custom_diffusion.py", line 731, in main
    assert (
AssertionError: Please run: python retrieve.py --class_prompt "dog" --class_data_dir real_reg/samples_dog --num_class_images 196
Traceback (most recent call last):
  File "/opt/.pyenv/versions/du_custom/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/.pyenv/versions/3.8.10/envs/du_custom/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/.pyenv/versions/3.8.10/envs/du_custom/lib/python3.8/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/opt/.pyenv/versions/3.8.10/envs/du_custom/lib/python3.8/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd`

**Comment by sjz1** [comment]
이 에러의 경우 두가지 해결 방법이 있습니다.

1. Single Concept인 경우
-> 단순히 받은 이미지의 개수가 196 이라면 num_classes를 196으로 설정하면 해결됩니다

2. Multi concept인 경우
-> num_classes를 두 컨셉을 동일하게 적용해야 하기 때문에  둘다 200개로 맞춰야 합니다
이 경우 custom diffusion의 공식레포 https://github.com/adobe-research/custom-diffusion를 clone 한 다음
`bash scripts/finetune_real.sh "cat" data/cat real_reg/samples_cat  cat finetune_addtoken.yaml <pretrained-model-path>
` 하라는 대로 돌리다 보면 reg data 가 자동으로 생긴다 (retrieve.py) 가 실행되서 (아니면 https://github.com/adobe-research/custom-diffusion/blob/main/src/retrieve.py 을 직접 이용해도 된다) 이유는 모르겠지만 이건 꽤나 잘 됩니다.
하지만 images path가 sample_cats/images/0.jpg 이런식으로 되야 정상 작동하는데 이 방식은 sample_cats/cats/0.jpg로 되어 있습니다
utils/edit.py에 간략한 코드를 만들어 놔서 파일경로를 바꾸고 실행한다음 cats->images로 디렉토리 name을 재지정하시면 됩니다
